const contractAddress = "0x1787641d110B5cF8F636578f54ec3d17748006D9"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to Lofi Lucies World";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Lofi Lucies World is a world full of music and all emotions an individual can have<br /> Every day in Lucies life is filled with new Lofi music <br /> The calender day you mint, will be your surprise NFT <br / follow on twitter for more to come <br /> <br /> <br /> <br /> <br /> <br /> The more you know about Lucie, the more you can enter parts of her world. She has a lot of friends, who send her new stuffed animals and merch. <br /> Lucie LOVES to share that merch ';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Lucies World is open";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "Everybody is allowed to mint";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your Lucie";
const mint_failed = "Minting failed. 😢 Please try again.";
